### ISSUE TITLE
autoescape for bootstrap form

### ISSUE THREAD

**Issue by gozzilli** [zsiciarz/django-envelope#52]
Upgrading from a very old version of python/django/django-envelope to latest, I scratched my head for a while before realising that the antispam field needed autoescaping or it would not render properly. All I was getting was a 400: `Rejected by spam_filter` as the honeypot field wasn't being sent.

Not sure if this is something new or if I'm doing something wrong, but this works for me:
```
{% autoescape off %}
{% antispam_fields %}
{% endautoescape %}
```

**Comment by elmq0022** [comment]
There was a break in the were simple_tag is treated differently now in django 1.9+ where the behavior is to autoescape the output.  The tag should probably be registered with a @register.inclusion_tag instead of @simple_tag.  

 looks like @richardbarran has taken over maintaining this to some degree.  Hopefully this update could be made in a future release.

**Comment by richardbarran** [comment]
Hi,
I've tried pinging the maintainer of django-envelope a few times, but without success, so in the meantime I've forked the package and put it on PyPI as per #55 
If someone wants to put the above bug fix into a PR then I'll gladly merge it and make a release of `django-envelope-updated` with the fix.
