### ISSUE TITLE
Add Mechanism To Prevent Form Resubmission

### ISSUE THREAD

**Issue by 9mido** [zsiciarz/django-envelope#61]
There should be a way to prevent a form from resubmitting again after a form processes and also double submission when a user clicks submit multiple times during a single form processing instance. A user should be able to set a period of time of how long until an authenticated user / anonymous user can be able to submit the form again. Sort of like a rate limiting / throttling mechanism.

**Comment by SebCorbin** [comment]
I aim to keep this module as simple as possible, the features your are requesting can be done outside of it:
 - Form resubmission is typically handled on the frontend (by disabling the submit button once clicked with javascript)
 - Throttling the form could be done with an override of the `clean()` method, and because there could be multiple conditions of throttling (on session, on IP adress, on email, etc), I prefer to let this integration outside of this package.
